services:
  postgres:
    image: postgres:16-alpine
    container_name: iot-postgres
    environment:
      POSTGRES_DB: iot
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_pass
    command: ["postgres", "-c", "max_connections=500"]
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
      - ./data/iot_telemetry_data.csv:/data/iot_telemetry_data.csv:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iot_user -d iot"]
      interval: 5s
      timeout: 5s
      retries: 10

  rest-service:
    build: ./rest-service
    container_name: iot-rest
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=iot;Username=iot_user;Password=iot_pass"
    depends_on:
      postgres:
        condition: service_healthy

  grpc-service:
    build: ./grpc-service
    container_name: iot-grpc
    ports:
      - "50051:50051"
    environment:
      DB_HOST: postgres
      DB_NAME: iot
      DB_USER: iot_user
      DB_PASS: iot_pass
    depends_on:
      postgres:
        condition: service_healthy

  graphql-service:
    build: ./graphql-service
    container_name: iot-graphql
    ports:
      - "5002:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=iot;Username=iot_user;Password=iot_pass"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
